# Configuration de l'application Streamlit
# À personnaliser selon votre déploiement

# URL de l'API - Production AWS EC2
API_URL = "http://16.171.134.145:8000"

# Pour test local (décommenter si besoin)
# API_URL = "http://localhost:8000"

# Exemples autres plateformes
# API_URL = "https://your-api-url.azurewebsites.net"
# API_URL = "https://your-app.herokuapp.com"
