# Configuration de l'application Streamlit
# À personnaliser selon votre déploiement

# URL de l'API - AWS EC2 (Production)
API_URL = "http://13.60.240.14:8000"

# Pour test local (décommenter si besoin)
# API_URL = "http://localhost:8000"

# Exemples autres plateformes
# API_URL = "https://your-api-url.azurewebsites.net"
# API_URL = "https://your-app.herokuapp.com"
